#!/usr/bin/env node
/**
 * Static prerender pass.
 *
 * Reads the built client `dist/index.html` template, renders each app route
 * through the SSR bundle at `dist-server/entry-server.js`, injects the
 * per-route Helmet head and React HTML into the template, and writes one
 * fully-formed HTML file per route.
 */
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  readdirSync,
  rmSync,
  existsSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import matter from "gray-matter";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const distDir = join(root, "dist");
const serverDir = join(root, "dist-server");
const blogDir = join(root, "src/content/blog");

const template = readFileSync(join(distDir, "index.html"), "utf8");

const { render } = await import(
  pathToFileURL(join(serverDir, "entry-server.js")).href
);

const slugs = readdirSync(blogDir)
  .filter((f) => f.endsWith(".mdx") && !f.startsWith("_"))
  .map((f) => matter(readFileSync(join(blogDir, f), "utf8")).data.slug)
  .filter(Boolean);

// Generated by scripts/fetch-episodes.mjs, which runs earlier in the build.
const episodesFile = join(root, "src/content/episodes.json");
const episodeSlugs = existsSync(episodesFile)
  ? JSON.parse(readFileSync(episodesFile, "utf8")).map((e) => e.slug)
  : [];

// Show notes live outside the client bundle, so each episode page is rendered
// with its own notes and carries a copy inline for hydration.
const notesFile = join(root, "src/content/episode-notes.json");
const allNotes = existsSync(notesFile)
  ? JSON.parse(readFileSync(notesFile, "utf8"))
  : {};

// Route -> output file (relative to dist/)
const routes = [
  { url: "/", out: "index.html" },
  { url: "/podcast", out: "podcast/index.html" },
  ...episodeSlugs.map((slug) => ({
    url: `/podcast/${slug}`,
    out: `podcast/${slug}/index.html`,
    notes: { [slug]: allNotes[slug] ?? "" },
  })),
  { url: "/blog", out: "blog/index.html" },
  ...slugs.map((slug) => ({
    url: `/blog/${slug}`,
    out: `blog/${slug}/index.html`,
  })),
  { url: "/404", out: "404.html" },
];

/**
 * Inline the notes ahead of the app bundle so they're set before hydration.
 * `<` is escaped because a literal `</script>` inside the JSON would otherwise
 * close this tag early.
 */
function notesScript(notes) {
  if (!notes) return "";
  const json = JSON.stringify(notes).replace(/</g, "\\u003c");
  return `\n    <script>window.__EPISODE_NOTES__=${json}</script>`;
}

function inject(tpl, { head, html, notes }) {
  return tpl
    .replace("<!--ssr-head-->", head + notesScript(notes))
    .replace("<!--ssr-outlet-->", html);
}

for (const route of routes) {
  const { html, head } = render(route.url, route.notes ?? {});
  const page = inject(template, { html, head, notes: route.notes });
  const outPath = join(distDir, route.out);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, page);
  console.log(`prerendered ${route.url} -> dist/${route.out}`);
}

// The SSR bundle is only needed at build time.
rmSync(serverDir, { recursive: true, force: true });

console.log(`prerendered ${routes.length} routes`);
