// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get_podcast_info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_podcast_info_default = defineTool({
  name: "get_podcast_info",
  title: "Get podcast info",
  description: "Return show metadata for the Human Endurance Podcast: description, hosts, and where to listen (Spotify, Apple Podcasts, YouTube).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Human Endurance Podcast",
      tagline: "Redefining Limits",
      description: "Endurance sports podcast exploring the science and stories behind human performance. Expert Series with specialists in sports science, nutrition, and coaching. Guest Series with real athletes doing extraordinary things while balancing everyday life.",
      website: "https://humanendurancepodcast.com",
      hosts: [
        {
          name: "Bruna",
          role: "Runner, Coach, and Co-founder of Augo Training",
          instagram: "https://www.instagram.com/justbrunathings/"
        },
        {
          name: "Fabi",
          role: "Triathlete, Coach, and Co-founder of Augo Training",
          instagram: "https://www.instagram.com/endurance_fabi/"
        }
      ],
      listen: {
        spotify: "https://open.spotify.com/show/4JR5cvFpYmuvaQxbx2D9nb",
        applePodcasts: "https://podcasts.apple.com/us/podcast/human-endurance/id1729061731",
        youtube: "https://www.youtube.com/@HumanEndurance"
      },
      social: {
        instagram: "https://www.instagram.com/humanendurancepodcast/",
        substack: "https://justbrunathings.substack.com/"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list_blog_posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var SITE = "https://humanendurancepodcast.com";
var list_blog_posts_default = defineTool2({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts on humanendurancepodcast.com (title, URL, publish date). Sourced from the live sitemap.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async () => {
    try {
      const res = await fetch(`${SITE}/sitemap.xml`, {
        headers: { Accept: "application/xml,text/xml" }
      });
      if (!res.ok) {
        return {
          content: [
            { type: "text", text: `Failed to fetch sitemap: HTTP ${res.status}` }
          ],
          isError: true
        };
      }
      const xml = await res.text();
      const urlBlocks = xml.match(/<url>[\s\S]*?<\/url>/g) ?? [];
      const posts = urlBlocks.map((block) => {
        const loc = block.match(/<loc>([^<]+)<\/loc>/)?.[1] ?? "";
        const lastmod = block.match(/<lastmod>([^<]+)<\/lastmod>/)?.[1];
        return { url: loc, lastmod };
      }).filter((entry) => /\/blog\/[^/]+$/.test(entry.url)).map((entry) => {
        const slug = entry.url.split("/blog/")[1] ?? "";
        const title = slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
        return { slug, title, url: entry.url, lastmod: entry.lastmod };
      });
      return {
        content: [
          { type: "text", text: JSON.stringify({ count: posts.length, posts }, null, 2) }
        ],
        structuredContent: { count: posts.length, posts }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Error: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/get_blog_post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var SITE2 = "https://humanendurancepodcast.com";
function stripHtml(html) {
  return html.replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<style[\s\S]*?<\/style>/gi, "").replace(/<[^>]+>/g, " ").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\s+/g, " ").trim();
}
var get_blog_post_default = defineTool3({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch a single blog post from humanendurancepodcast.com/blog/<slug>. Returns title, description, and readable text.",
  inputSchema: {
    slug: z.string().min(1).describe("The blog post slug, e.g. 'welcome-to-the-blog'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ slug }) => {
    const safe = slug.replace(/[^a-z0-9-]/gi, "");
    const url = `${SITE2}/blog/${safe}`;
    try {
      const res = await fetch(url);
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `HTTP ${res.status} for ${url}` }],
          isError: true
        };
      }
      const html = await res.text();
      const title = html.match(/<title>([^<]+)<\/title>/i)?.[1]?.trim() ?? "";
      const description = html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)/i)?.[1]?.trim() ?? "";
      const main = html.match(/<article[\s\S]*?<\/article>/i)?.[0] ?? html;
      const text = stripHtml(main).slice(0, 8e3);
      const post = { slug: safe, url, title, description, text };
      return {
        content: [{ type: "text", text: JSON.stringify(post, null, 2) }],
        structuredContent: post
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Error: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "human-endurance-podcast-mcp",
  title: "Human Endurance Podcast",
  version: "0.1.0",
  instructions: "Public tools for the Human Endurance Podcast. Use `get_podcast_info` for show metadata, hosts, and listen links. Use `list_blog_posts` to discover blog posts on humanendurancepodcast.com, then `get_blog_post` with a slug to read one.",
  tools: [get_podcast_info_default, list_blog_posts_default, get_blog_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
